const fs = require('fs');

/**
 * Parses G-code files generated by PrusaSlicer to extract printing metrics.
 * @param {string} filePath Path to the .gcode file
 * @returns {Object} Extracted metrics
 */
function parseGCode(filePath) {
    try {
        const content = fs.readFileSync(filePath, 'utf8');
        const lines = content.split('\n');
        
        // PrusaSlicer usually puts these at the very end
        const lastLines = lines.slice(-200).join('\n');
        
        let grams = 0;
        let timeMinutes = 0;
        let lengthMm = 0;

        // Extracting mass (g)
        const massMatch = lastLines.match(/filament used \[g\] = ([\d\.]+)/);
        if (massMatch) {
            grams = parseFloat(massMatch[1]);
        }

        // Extracting length (mm)
        const lengthMatch = lastLines.match(/filament used \[mm\] = ([\d\.]+)/);
        if (lengthMatch) {
            lengthMm = parseFloat(lengthMatch[1]);
        }

        // Extracting estimated time
        // Format: "1h 23m 45s" or "23m 45s"
        const timeMatch = lastLines.match(/estimated printing time \(normal mode\) = ([^\n]+)/);
        if (timeMatch) {
            const timeStr = timeMatch[1].trim();
            const hours = timeStr.match(/(\d+)h/) ? parseInt(timeStr.match(/(\d+)h/)[1]) : 0;
            const minutes = timeStr.match(/(\d+)m/) ? parseInt(timeStr.match(/(\d+)m/)[1]) : 0;
            const seconds = timeStr.match(/(\d+)s/) ? parseInt(timeStr.match(/(\d+)s/)[1]) : 0;
            
            timeMinutes = (hours * 60) + minutes + (seconds / 60);
        }

        return {
            success: true,
            grams: parseFloat(grams.toFixed(2)),
            timeMinutes: parseFloat(timeMinutes.toFixed(2)),
            lengthMm: parseFloat(lengthMm.toFixed(2)),
            cost: 0 // Will be calculated by pricing service
        };
    } catch (error) {
        console.error('[PARSER-ERR] Error parsing G-code:', error.message);
        return { success: false, error: error.message };
    }
}

module.exports = { parseGCode, parseGcode: parseGCode };
